#!/usr/bin/env python3
"""
文档切片策略对比测试
比较不同的切片方法：Token、Sentence、SentenceWindow、Semantic
"""

import os
import sys

# UTF-8输出（Windows兼容）
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

from llama_index.core import VectorStoreIndex, Settings, Document
from llama_index.core.node_parser import (
    SentenceWindowNodeParser,
    SemanticSplitterNodeParser,
    TokenTextSplitter,
    SentenceSplitter
)
from llama_index.core.postprocessor import MetadataReplacementPostProcessor

# 导入 OpenAI LLM (用于 DashScope 兼容模式)
from llama_index.llms.openai import OpenAI
# 导入 DashScopeEmbedding
from llama_index.embeddings.dashscope import DashScopeEmbedding

# 获取 API Key
DASHSCOPE_API_KEY = os.getenv("DASHSCOPE_API_KEY")

print("="*70)
print("文档切片策略对比测试")
print("="*70)

# 初始化 LlamaIndex 全局设置
if DASHSCOPE_API_KEY:
    try:
        print("\n✓ 配置 LLM 和 Embedding...")

        # 1. 配置 LLM (使用 DashScope 的 qwen-plus 模型)
        Settings.llm = OpenAI(
            model="qwen-plus",
            api_base="https://dashscope.aliyuncs.com/compatible-mode/v1",
            api_key=DASHSCOPE_API_KEY,
            temperature=0.1
        )

        # 2. 配置嵌入模型
        Settings.embed_model = DashScopeEmbedding(
            model_name="text-embedding-v2",
            api_key=DASHSCOPE_API_KEY,
        )

        print("  ✓ LLM: qwen-plus")
        print("  ✓ Embedding: text-embedding-v2")
    except Exception as e:
        print(f"  ⚠ 配置失败（本测试只查看切片，不影响）: {e}")
else:
    print("\n⚠ 未找到 DASHSCOPE_API_KEY，本测试只展示切片效果")


def evaluate_splitter(splitter, documents, splitter_name):
    """
    评测不同文档切片方法的效果
    手动打印召回结果，方便直接对比切分效果。
    """
    print(f"\n{'='*70}")
    print(f"【{splitter_name}】切片方法")
    print(f"{'='*70}\n")

    # 显示 raw chunks generated by the splitter
    print(f"生成的文档切片 (Nodes):\n")
    raw_nodes = splitter.get_nodes_from_documents(documents)

    print(f"总共生成 {len(raw_nodes)} 个切片\n")

    for i, node in enumerate(raw_nodes, 1):
        content = node.get_content()
        content_preview = content[:150].replace('\n', ' ') + "..." if len(content) > 150 else content.replace('\n', ' ')

        print(f"{'─'*70}")
        print(f"切片 {i} (长度: {len(content)} 字符)")
        print(f"{'─'*70}")

        if isinstance(splitter, SentenceWindowNodeParser):
            # For Sentence Window, show metadata
            original_text = node.metadata.get("original_text", "N/A")
            window = node.metadata.get("window", "N/A")

            print(f"核心句子: {original_text[:100]}...")
            print(f"\n窗口上下文长度: {len(window) if window != 'N/A' else 0} 字符")
            print(f"预览: {content_preview}")
        else:
            print(f"{content_preview}")

        # 显示部分元数据
        if node.metadata:
            print(f"\n元数据: {list(node.metadata.keys())}")

        print()

    print(f"{'='*70}")
    print(f"{splitter_name} 测试完成\n")


# --- 示例文档 ---
documents = [
    Document(
        text="""
        LlamaIndex 是一个用于构建 LLM 应用程序的数据框架。
        它提供了一套工具，可以帮助开发者将私有数据与大型语言模型（LLMs）连接起来，
        实现包括问答、检索增强生成（RAG）等功能。
        LlamaIndex 支持多种数据源，包括 PDF、数据库、API 等。
        其核心概念包括文档加载器、节点解析器、索引和查询引擎。

        文档加载器负责将各种格式和来源的数据摄取到 LlamaIndex 中。
        节点解析器随后将这些加载的文档分解成更小、更易于管理的单元，称为节点。
        这些节点通常是句子或段落，具体取决于解析策略。
        索引是构建在这些节点之上的数据结构，旨在实现高效存储和检索，
        通常涉及向量嵌入以进行语义搜索。
        最后，查询引擎促进了与索引数据的交互，允许用户提出问题
        并利用 LLM 和检索到的信息合成答案。

        --- 以下是与 LlamaIndex 主题不太直接相关的内容 ---

        此外，Python 作为一门通用编程语言，其简洁性和丰富的库生态使其在 AI 领域广受欢迎。
        例如，NumPy 和 Pandas 是数据处理的基础，它们提供了强大的工具用于数值操作和结构化数据。
        Scikit-learn 则提供了全面的机器学习算法套件，适用于分类、回归和聚类等任务。
        这些工具共同构成了数据科学家和 AI 从业者的强大工具箱，
        使他们能够高效地开发和部署复杂的 AI 模型。

        --- 以下是另一个相关但概念上独立的部分 ---

        句子窗口切片是一种高级的切片策略，它在每个切片中包含一个目标句子，
        并在其前后添加一定数量的"窗口"句子作为上下文。
        这种方法旨在检索时为 LLM 提供丰富的局部上下文，从而提高生成答案的连贯性。
        语义切片则尝试根据文本的语义内容来划分段落，
        而不是仅仅依靠固定的字符数或句子数量。
        它利用嵌入模型计算句子或短语之间的语义相似度，
        识别出主题或含义发生自然转变的断点。
        这两种高级方法都能有效提升 RAG 应用的召回和生成质量。
        选择正确的切片策略通常取决于数据的具体特征和预期的查询类型。
        """
    )
]

print("\n📄 测试文档信息:")
print(f"  文档数量: {len(documents)}")
print(f"  文档总长度: {len(documents[0].text)} 字符")
print()

# --- 测试不同的切片策略 ---

# 1. Token 切片 - 小块，无重叠
print("\n" + "🔹"*35)
print("测试 1: Token 切片 (固定大小)")
print("🔹"*35)
token_splitter_small = TokenTextSplitter(
    chunk_size=30,   # 小chunk演示
    chunk_overlap=0  # 无重叠
)
evaluate_splitter(token_splitter_small, documents, "Token切片 (size=30, overlap=0)")

# 2. Token 切片 - 小块，有重叠
token_splitter_overlap = TokenTextSplitter(
    chunk_size=30,
    chunk_overlap=10  # 有重叠
)
evaluate_splitter(token_splitter_overlap, documents, "Token切片 (size=30, overlap=10)")

# 3. Sentence 切片 - 中等大小
print("\n" + "🔹"*35)
print("测试 2: Sentence 切片 (句子边界)")
print("🔹"*35)
sentence_splitter = SentenceSplitter(
    chunk_size=200,   # 按token计算
    chunk_overlap=20
)
evaluate_splitter(sentence_splitter, documents, "Sentence切片 (size=200, overlap=20)")

# 4. Sentence Window 切片
print("\n" + "🔹"*35)
print("测试 3: Sentence Window 切片 (带上下文窗口)")
print("🔹"*35)
sentence_window_splitter = SentenceWindowNodeParser(
    window_size=3,           # 前后各3个句子
    window_metadata_key="window",
    original_text_metadata_key="original_text"
)
evaluate_splitter(sentence_window_splitter, documents, "SentenceWindow切片 (window=3)")

# 5. Semantic 切片 (需要embedding)
if DASHSCOPE_API_KEY:
    print("\n" + "🔹"*35)
    print("测试 4: Semantic 切片 (语义边界)")
    print("🔹"*35)
    try:
        semantic_splitter = SemanticSplitterNodeParser(
            buffer_size=1,           # 句子缓冲
            breakpoint_percentile_threshold=95,  # 断点阈值
            embed_model=Settings.embed_model
        )
        evaluate_splitter(semantic_splitter, documents, "Semantic切片 (语义驱动)")
    except Exception as e:
        print(f"  ⚠ Semantic切片测试失败: {e}")
else:
    print("\n⚠ 跳过 Semantic 切片测试（需要 DASHSCOPE_API_KEY）")

print("\n" + "="*70)
print("✅ 所有切片策略测试完成！")
print("="*70)
print("\n💡 总结:")
print("  - Token切片: 固定大小，可能切断句子")
print("  - Sentence切片: 尊重句子边界，更自然")
print("  - SentenceWindow切片: 保留上下文窗口，适合需要前后文的场景")
print("  - Semantic切片: 根据语义相似度切分，最智能但需要embedding")
